using System;
using System.Collections.Generic;

namespace IDataAPI.Models_NEW
{
    public partial class SalePricesMsa
    {
        public double RegionId { get; set; }
        public string RegionName { get; set; }
        public double? SizeRank { get; set; }
        public double? Mar08 { get; set; }
        public double? Apr08 { get; set; }
        public double? May08 { get; set; }
        public double? Jun08 { get; set; }
        public double? Jul08 { get; set; }
        public double? Aug08 { get; set; }
        public double? Sep08 { get; set; }
        public double? Oct08 { get; set; }
        public double? Nov08 { get; set; }
        public double? Dec08 { get; set; }
        public double? Jan09 { get; set; }
        public double? Feb09 { get; set; }
        public double? Mar09 { get; set; }
        public double? Apr09 { get; set; }
        public double? May09 { get; set; }
        public double? Jun09 { get; set; }
        public double? Jul09 { get; set; }
        public double? Aug09 { get; set; }
        public double? Sep09 { get; set; }
        public double? Oct09 { get; set; }
        public double? Nov09 { get; set; }
        public double? Dec09 { get; set; }
        public double? Jan10 { get; set; }
        public double? Feb10 { get; set; }
        public double? Mar10 { get; set; }
        public double? Apr10 { get; set; }
        public double? May10 { get; set; }
        public double? Jun10 { get; set; }
        public double? Jul10 { get; set; }
        public double? Aug10 { get; set; }
        public double? Sep10 { get; set; }
        public double? Oct10 { get; set; }
        public double? Nov10 { get; set; }
        public double? Dec10 { get; set; }
        public double? Jan11 { get; set; }
        public double? Feb11 { get; set; }
        public double? Mar11 { get; set; }
        public double? Apr11 { get; set; }
        public double? May11 { get; set; }
        public double? Jun11 { get; set; }
        public double? Jul11 { get; set; }
        public double? Aug11 { get; set; }
        public double? Sep11 { get; set; }
        public double? Oct11 { get; set; }
        public double? Nov11 { get; set; }
        public double? Dec11 { get; set; }
        public double? Jan12 { get; set; }
        public double? Feb12 { get; set; }
        public double? Mar12 { get; set; }
        public double? Apr12 { get; set; }
        public double? May12 { get; set; }
        public double? Jun12 { get; set; }
        public double? Jul12 { get; set; }
        public double? Aug12 { get; set; }
        public double? Sep12 { get; set; }
        public double? Oct12 { get; set; }
        public double? Nov12 { get; set; }
        public double? Dec12 { get; set; }
        public double? Jan13 { get; set; }
        public double? Feb13 { get; set; }
        public double? Mar13 { get; set; }
        public double? Apr13 { get; set; }
        public double? May13 { get; set; }
        public double? Jun13 { get; set; }
        public double? Jul13 { get; set; }
        public double? Aug13 { get; set; }
        public double? Sep13 { get; set; }
        public double? Oct13 { get; set; }
        public double? Nov13 { get; set; }
        public double? Dec13 { get; set; }
        public double? Jan14 { get; set; }
        public double? Feb14 { get; set; }
        public double? Mar14 { get; set; }
        public double? Apr14 { get; set; }
        public double? May14 { get; set; }
        public double? Jun14 { get; set; }
        public double? Jul14 { get; set; }
        public double? Aug14 { get; set; }
        public double? Sep14 { get; set; }
        public double? Oct14 { get; set; }
        public double? Nov14 { get; set; }
        public double? Dec14 { get; set; }
        public double? Jan15 { get; set; }
        public double? Feb15 { get; set; }
        public double? Mar15 { get; set; }
        public double? Apr15 { get; set; }
        public double? May15 { get; set; }
        public double? Jun15 { get; set; }
        public double? Jul15 { get; set; }
        public double? Aug15 { get; set; }
        public double? Sep15 { get; set; }
        public double? Oct15 { get; set; }
        public double? Nov15 { get; set; }
        public double? Dec15 { get; set; }
        public double? Jan16 { get; set; }
        public double? Feb16 { get; set; }
        public double? Mar16 { get; set; }
        public double? Apr16 { get; set; }
        public double? May16 { get; set; }
        public double? Jun16 { get; set; }
        public double? Jul16 { get; set; }
        public double? Aug16 { get; set; }
        public double? Sep16 { get; set; }
        public double? Oct16 { get; set; }
        public double? Nov16 { get; set; }
        public double? Dec16 { get; set; }
        public double? Jan17 { get; set; }
        public double? Feb17 { get; set; }
        public double? Mar17 { get; set; }
        public double? Apr17 { get; set; }
        public double? May17 { get; set; }
        public double? Jun17 { get; set; }
        public double? Jul17 { get; set; }
        public double? Aug17 { get; set; }
        public double? Sep17 { get; set; }
        public double? Oct17 { get; set; }
        public double? Nov17 { get; set; }
        public double? Dec17 { get; set; }
        public double? Jan18 { get; set; }
        public double? Feb18 { get; set; }
        public double? Mar18 { get; set; }
    }
}
